[package]
name = "rcwt_vm"
version = "0.1.0"
authors = ["sKyrBBit <iamskyrabbit@gmail.com>"]
edition = "2018"

[dependencies]
paste = "0.1.12"
serde = { version = "1.0.115", features = ["derive"] }

[build-dependencies]
cc = "1.0.53"
