[package]
name = "rcwt_cli"
version = "0.1.0"
authors = ["sKyrBBit <iamskyrabbit@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
paste = "0.1.18"
serde = { version = "1.0.115", features = ["derive"] }
serde_yaml = "0.8.13"
rcwt_vm = { path = "../rcwt_vm" }