name: RRCWT

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --verbose
  build_on_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --verbose